import React, { useCallback, useEffect, useState } from 'react';
import { Alert, Button, Modal, Platform, ScrollView, Text, TextInput } from 'react-native';
import { useRouter } from 'expo-router';
import { acceptReveal, breakBottle, getBottleById, getRevealStatus, refuseReveal, reportBottleConversation, requestReveal } from '../api/bottles';
import { getMatch } from '../api/matches';
import { useStore } from '../store/useStore';

type ReportReason = 'HARASSMENT' | 'SPAM' | 'FAKE' | 'INAPPROPRIATE_CONTENT' | 'MINOR' | 'OTHER';
const REASONS: Array<{value: ReportReason; label: string}> = [{value:'HARASSMENT',label:'Harcèlement'},{value:'SPAM',label:'Spam'},{value:'FAKE',label:'Profil fake'},{value:'INAPPROPRIATE_CONTENT',label:'Contenu inapproprié'},{value:'MINOR',label:'Mineur'},{value:'OTHER',label:'Autre'}];
type Props = { visible:boolean; bottleId:string; canBreak:boolean; onClose:()=>void; onRefresh:()=>Promise<void>|void; onBroken:()=>void };

export const BottleCorrespondenceMenu: React.FC<Props> = ({visible,bottleId,canBreak,onClose,onRefresh,onBroken}) => {
  const router=useRouter(); const currentUser=useStore(s=>s.currentUser);
  const [status,setStatus]=useState<any>(null); const [partnerId,setPartnerId]=useState<string|null>(null); const [loading,setLoading]=useState(false);
  const [report,setReport]=useState(false); const [reason,setReason]=useState<ReportReason|''>(''); const [details,setDetails]=useState('');
  const msg=(t:string,x:string)=>Platform.OS==='web'&&typeof globalThis.alert==='function'?globalThis.alert(`${t}\n\n${x}`):Alert.alert(t,x);
  const load=useCallback(async()=>{const[s,b]=await Promise.all([getRevealStatus(bottleId),getBottleById(bottleId)]);setStatus({...s,bottleStatus:b.status});let id:string|null=null;if(b.matchId){try{id=(await getMatch(b.matchId)).otherUserId;}catch{}}if(!id&&currentUser?.id)id=b.senderId===currentUser.id?b.acceptedById:b.senderId;if(!id&&s.hasPendingRequest&&!s.isRequester)id=s.requestedById??null;setPartnerId(id);},[bottleId,currentUser?.id]);
  useEffect(()=>{if(!visible)return;load().catch(e=>msg('Erreur',e?.message||'Chargement impossible'));const i=setInterval(()=>load().catch(()=>{}),3000);return()=>clearInterval(i);},[visible,load]);
  const refresh=async()=>{await load();await onRefresh();};
  const openProfile=(id=partnerId)=>{if(!id)return msg('Erreur','Profil partenaire introuvable');onClose();router.push(`/profile/${id}?source=bottle&bottleId=${encodeURIComponent(bottleId)}` as never);};
  const request=async()=>{if(!canBreak)return msg('Dévoilement indisponible','Une première lettre chacun est nécessaire.');setLoading(true);try{await requestReveal(bottleId);await refresh();msg('Dévoilement','Demande envoyée.');onClose();}catch(e:any){msg('Erreur',e?.message||'Demande impossible');}finally{setLoading(false);}};
  const accept=async()=>{setLoading(true);try{let id=partnerId||status?.requestedById;const r=await acceptReveal(bottleId);if(r.matchId){try{id=(await getMatch(r.matchId)).otherUserId;}catch{}}await onRefresh();msg('Dévoilement','Dévoilement accepté.');openProfile(id);}catch(e:any){msg('Erreur',e?.message||'Acceptation impossible');}finally{setLoading(false);}};
  const refuse=async()=>{setLoading(true);try{await refuseReveal(bottleId);await refresh();msg('Dévoilement','Dévoilement refusé.');onClose();}catch(e:any){msg('Erreur',e?.message||'Refus impossible');}finally{setLoading(false);}};
  const breakIt=async()=>{try{await breakBottle(bottleId);onClose();onBroken();}catch(e:any){msg('Erreur',e?.message||'Rupture impossible');}};
  const submitReport=async()=>{if(!reason)return;setLoading(true);try{await reportBottleConversation(bottleId,reason,details.trim()||undefined);setReason('');setDetails('');setReport(false);msg('Signalement','Signalement envoyé.');}catch(e:any){msg('Erreur',e?.message||'Signalement impossible');}finally{setLoading(false);}};
  return <><Modal visible={visible} onRequestClose={onClose}><ScrollView><Text>Actions de correspondance</Text>{loading&&<Text>Chargement...</Text>}{status?.bottleStatus==='REVEALED'?<Button title="Voir le profil dévoilé" onPress={()=>openProfile()}/>:!canBreak?<Text>Dévoilement disponible après une première lettre chacun.</Text>:!status?.hasPendingRequest?<Button title="Demander le dévoilement" onPress={request}/>:status?.isRequester?<Text>Demande de dévoilement en attente.</Text>:<><Button title="Accepter le dévoilement" onPress={accept}/><Button title="Refuser le dévoilement" onPress={refuse}/></>}{canBreak&&<Button title="Arrêter la correspondance" onPress={()=>{if(Platform.OS==='web'){if(globalThis.confirm('Fermer définitivement cette discussion ?'))breakIt();}else Alert.alert('Rompre cette correspondance ?','Cela fermera définitivement la discussion.',[{text:'Annuler'},{text:'Rompre',onPress:breakIt}]);}}/>}<Button title="Signaler" onPress={()=>setReport(true)}/><Button title="Fermer" onPress={onClose}/></ScrollView></Modal><Modal visible={report} onRequestClose={()=>setReport(false)}><ScrollView><Text>Signaler cette conversation</Text><Text>Raison : {reason||'aucune'}</Text>{REASONS.map(r=><Button key={r.value} title={r.label} onPress={()=>setReason(r.value)}/>)}<TextInput placeholder="Détails supplémentaires (optionnel)" value={details} onChangeText={setDetails} multiline maxLength={500}/><Text>{details.length}/500</Text><Button title="Envoyer le signalement" disabled={!reason||loading} onPress={submitReport}/><Button title="Annuler" onPress={()=>setReport(false)}/></ScrollView></Modal></>;
};
