import React from 'react';
import { Button, ScrollView, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
type Mode='terms'|'privacy'; interface Section{title:string;paragraphs:string[]}
const TERMS:Section[]=[
{title:'1. Objet',paragraphs:["JeuTaime est une application sociale et de rencontre qui privilégie les échanges progressifs, les lettres, les salons, les mécaniques de découverte et les interactions ludiques avant le dévoilement complet des profils.","Les présentes conditions encadrent l'accès et l'utilisation de l'application et de ses services."]},
{title:'2. Conditions d’accès',paragraphs:["L’inscription est réservée aux personnes majeures. L’utilisateur s’engage à fournir des informations sincères et à ne pas usurper l’identité d’un tiers.","Les identifiants de connexion sont personnels. Toute utilisation du compte est réputée effectuée par son titulaire tant qu’un accès frauduleux n’a pas été signalé."]},
{title:'3. Fonctionnement de JeuTaime',paragraphs:["JeuTaime propose notamment la découverte de profils, les Sourires et Grimaces, le jeu des 3 questions, les lettres, les salons, la Bouteille à la mer, le Refuge, les offrandes, le Profil de la semaine, les notifications et différentes mécaniques sociales.","Certaines fonctionnalités peuvent être limitées, débloquées progressivement, réservées à une formule payante ou dépendre d’un solde de pièces virtuelles.","JeuTaime ne garantit ni rencontre, ni réponse, ni compatibilité entre utilisateurs."]},
{title:'4. Comportement des utilisateurs',paragraphs:["Sont interdits les comportements illégaux, menaçants, haineux, discriminatoires, harcelants, frauduleux ou portant atteinte à la sécurité d’autrui.","Il est également interdit de publier ou transmettre des contenus illicites, de contourner les systèmes de sécurité, d’automatiser abusivement l’utilisation du service ou de tenter d’accéder aux données d’autres utilisateurs.","Les fonctions de blocage et de signalement sont mises à disposition pour contribuer à la sécurité de la communauté."]},
{title:'5. Contenus publiés',paragraphs:["L’utilisateur reste responsable des textes, photos, messages et autres contenus qu’il transmet via JeuTaime. Il doit disposer des droits nécessaires pour les utiliser.","Les contenus peuvent être modérés, masqués ou supprimés lorsqu’ils enfreignent les présentes conditions, la loi ou les règles de sécurité de l’application."]},
{title:'6. Pièces, offres et Premium',paragraphs:["Les pièces sont une unité virtuelle interne à JeuTaime. Elles ne constituent pas une monnaie, n’ont pas de valeur monétaire hors du service et ne peuvent pas être converties librement en argent réel.","Les caractéristiques, tarifs, avantages et conditions des formules payantes doivent être affichés avant toute souscription. Les paiements en monnaie réelle ne doivent être considérés comme disponibles que lorsqu’un parcours de paiement officiellement activé est présenté dans l’application."]},
{title:'7. Modération et suspension',paragraphs:["JeuTaime peut prendre des mesures proportionnées en cas d’abus, notamment limitation de fonctionnalités, suspension ou bannissement du compte, conformément aux règles applicables et aux nécessités de sécurité.","L’utilisateur peut également désactiver son compte depuis les paramètres et le réactiver ultérieurement en se reconnectant, ou demander sa suppression définitive via la fonction dédiée."]},
{title:'8. Disponibilité du service',paragraphs:["Le service peut évoluer, être interrompu temporairement pour maintenance, sécurité ou correction d’incidents. JeuTaime s’efforce de préserver la continuité du service sans pouvoir garantir une disponibilité permanente."]},
{title:'9. Propriété intellectuelle',paragraphs:["L’application, son identité visuelle, ses interfaces, textes éditoriaux, illustrations, logiciels et éléments graphiques restent protégés par les droits applicables, sous réserve des droits appartenant à leurs auteurs ou fournisseurs respectifs."]},
{title:'10. Éditeur et droit applicable',paragraphs:["À COMPLÉTER AVANT PUBLICATION : identité juridique de l’éditeur, forme sociale, adresse, SIRET/RCS le cas échéant, contact, directeur de la publication, hébergeur et juridiction/droit applicable."]}];
const PRIVACY:Section[]=[
{title:'1. Responsable du traitement',paragraphs:["À COMPLÉTER AVANT PUBLICATION : identité et coordonnées du responsable du traitement JeuTaime, ainsi que l’adresse de contact dédiée aux demandes relatives aux données personnelles et, le cas échéant, les coordonnées du DPO."]},
{title:'2. Données traitées',paragraphs:["Selon les fonctionnalités utilisées, JeuTaime peut traiter les données de compte, les données de profil et les réglages de confidentialité.","L’application traite également les interactions nécessaires au service : Sourires/Grimaces, matchs, lettres, salons, Bouteille à la mer, Refuge, offrandes, votes, blocages, signalements, notifications, support et historique des pièces.","JeuTaime ne doit pas demander de géolocalisation précise lorsque la fonctionnalité concernée n’en a pas besoin. Le partage de la ville est contrôlable depuis les réglages."]},
{title:'3. Finalités',paragraphs:["Les données sont utilisées pour administrer le compte, fournir les fonctionnalités, afficher les profils compatibles, permettre les échanges, gérer abonnements et pièces, assurer la sécurité, prévenir les abus, traiter les signalements et fournir le support."]},
{title:'4. Bases juridiques',paragraphs:["Selon le traitement, la base juridique peut être l’exécution du service, une obligation légale, l’intérêt légitime lié à la sécurité ou le consentement lorsqu’il est requis."]},
{title:'5. Destinataires et sous-traitants',paragraphs:["Des prestataires techniques peuvent intervenir pour l’hébergement, les notifications, le stockage, le paiement ou d’autres fonctions nécessaires.","À COMPLÉTER AVANT PUBLICATION : liste ou catégories définitives des prestataires, localisation des traitements et garanties des éventuels transferts hors EEE."]},
{title:'6. Durées de conservation',paragraphs:["Les données ne doivent être conservées que pendant une durée nécessaire aux finalités décrites, puis supprimées ou archivées lorsque la loi l’exige.","À COMPLÉTER AVANT PUBLICATION : durées précises par catégorie."]},
{title:'7. Tes choix de confidentialité',paragraphs:["Depuis les paramètres, l’utilisateur peut notamment contrôler sa présence dans la découverte, le partage de sa ville et les notifications push lorsque ces réglages sont disponibles."]},
{title:'8. Tes droits',paragraphs:["L’utilisateur peut, dans les conditions prévues par la réglementation, demander l’accès, la rectification, l’effacement, la limitation, l’opposition et la portabilité lorsque celle-ci s’applique.","JeuTaime propose un export des données personnelles et une fonction de suppression définitive du compte.","À COMPLÉTER AVANT PUBLICATION : adresse de contact pour l’exercice des droits. L’utilisateur peut également saisir la CNIL."]},
{title:'9. Sécurité',paragraphs:["JeuTaime met en œuvre des mesures techniques et organisationnelles destinées à protéger les comptes et données contre les accès non autorisés, la perte, l’altération ou la divulgation."]},
{title:'10. Mise à jour de la politique',paragraphs:["Cette politique peut être mise à jour lorsque les fonctionnalités, prestataires ou obligations réglementaires évoluent."]}];
export default function LegalDocumentScreen({mode}:{mode:Mode}){const router=useRouter();const isPrivacy=mode==='privacy';const sections=isPrivacy?PRIVACY:TERMS;return <ScrollView><Text>{isPrivacy?'Politique de confidentialité':"Conditions d’utilisation"}</Text><Text>Version de préparation — 7 août 2026</Text><Text>Document provisoire. Les informations « À COMPLÉTER » doivent être renseignées et relues avant publication commerciale.</Text>{sections.map(section=><View key={section.title}><Text>{section.title}</Text>{section.paragraphs.map((p,i)=><Text key={`${section.title}-${i}`}>{p}</Text>)}</View>)}<Button title="Retour" onPress={()=>router.back()}/></ScrollView>;}
